### ISSUE TITLE
It should be possible to validate long urls

### ISSUE THREAD

**Issue by martinpeck** [martinpeck/plinky#2]
It should be possible to review the long urls and test that they exist, to prevent urls become stale/dead over time.

**Comment by ArunVenkata** [comment]
Yes it is possible by using httplib2. I want to work on this issue.

**Comment by martinpeck** [comment]
Pull requests welcome! However, I wonder if validation is actually worth doing, as it'll require an additional network round trip. It might actually be better to just test the short links with an external tool, at build/deploy time.

**Comment by martinpeck** [comment]
It might make sense to propose a solution, before implementing something.

**Comment by ArunVenkata** [comment]
We could use something of this sort


def __url_exist_check(self):
        try:
            resp = httplib2.Http().request(self.__url, 'HEAD')
            assert int(resp[0]['status']) < 400
            return int(resp[0]['status'])
        except AssertionError:
            return "NOT FOUND!"

**Comment by ArunVenkata** [comment]
A similar head request could be made for the website.

**Comment by ArunVenkata** [comment]
It Doesn't seem like there's a way to validate the url without having to use the network.

**Comment by martinpeck** [comment]
I suspect this was a bad idea on my part.

I don't think that URLs should be checked as the user invokes a short url. When someone visits a short URL, Plink should do as little as possible and should not get in the way of the user's goal (being redirected to the long URL). Even if we *did* check the validity of a URL at this point, it's too late. If the URL is invalid (returning a 500, 404, or some other error) then what can we do, other then return that error to the user?

The other issue is that Plinky's view of the URL might not match the user's view. Content might be restricted, or geo-fenced, and so Plinky may see a different response to the end user. 

So, the only way to meaningfully validate the URLs is as part of a build/test process. Either at deploy time, or periodically, a test could be run to check ALL the URLs and report on those that appeared broken.

I suspect this was a good idea at the time, but having thought about it more it's not something that Plinky should implement directly.

**Comment by martinpeck** [comment]
@ArunVenkata thanks for the offer to contribute some code changes here. I'm pretty sure I'm going to close this issue now that I've thought through the user experience.
